version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - db_data:/app/database
    depends_on:
      - db

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - db_data:/data

volumes:
  db_data:
